import { API_URL } from '../globals.js'

class Task extends HTMLElement {
    constructor() {
        super();
        this.shadowDOM = this.attachShadow({mode: 'open'});
    }

    /**
     * Lifecycle method called when the custom element is appended to the document.
     * It maps component attributes, renders the component, and initializes it.
     */
    connectedCallback() {
        this.mapComponentAttributes();
        this.render();
        this.initComponent();
    }

    /**
     * Maps component attributes to ensure they have default values.
     * If an attribute is not present, it initializes it with an empty string.
     * 
     * @method mapComponentAttributes
     * @memberof TaskComponent
     * @private
     */
    mapComponentAttributes() {
        const attributesMapping = [
            'name',
            'description',
            'done',
            'task-id'
        ];
        attributesMapping.forEach(key => {
            if (!this.attributes[key]) {
                this.attributes[key] = { value: '' };
            }
        });
    }

    /**
     * Renders the component by setting the inner HTML of the shadow DOM.
     * It combines the CSS and HTML templates generated by the templateCss and template methods.
     */
    render() {
        this.shadowDOM.innerHTML = `
            ${this.templateCss()}
            ${this.template()}
        `;
    }

    /**
     * Generates the HTML template for a task component.
     *
     * @returns {string} The HTML string representing the task component.
     * @property {string} attributes.name.value - The name of the task.
     * @property {string} attributes.description.value - The description of the task.
     * @property {string} attributes.done.value - The completion status of the task ('true' or 'false').
     */
    template() {
        const name = this.attributes.name.value;
        const description = this.attributes.description.value;
        const done = this.attributes.done.value === 'true';

        return `
            <li class="task">
                <h2 class="task-name">${name}</h2>
                <p class="task-description">${description}</p>
                <app-button class="toggle-done-button" color="${done ? 'secondary' : 'primary'}">${done ? 'Undone' : 'Done'}</app-button>
                <app-button class="delete-button" color="danger">Delete</app-button>
            </li>
        `;
    }
 
    /**
     * Generates a template string containing CSS styles for the button component.
     * 
     * @returns {string} A template string containing the CSS styles.
     */
    templateCss() {
        return `
            <style>
                * {
                    box-sizing: border-box;
                }

                .task {
                    --min-task-height: 3.75rem;

                    display: grid;
                    background-color: var(--content-1);
                    border: 2px solid var(--content-4);

                    align-items: center;
                    grid-template-rows: min-content 1fr;
                    grid-template-columns: 1fr auto auto;

                    min-height: var(--min-task-height);
                    padding: 0.75rem;
                    border-radius: 0.5rem;

                    gap: 0 0.75rem;
                    
                    list-style: none;
                }

                .task-name {
                    font-size: 1.2rem;
                    font-weight: bold;
                    line-height: 0.5rem;
                    height: 0.5rem;

                    grid-column: 1 / 2;
                }

                .task-description {
                    font-size: 1rem;
                    line-height: 0.5rem;

                    grid-column: 1 / 2;
                }

                .toggle-done-button {
                    width: 100%;
                    justify-self: end;

                    grid-column: 2 / 3;
                    grid-row: 1 / 3;
                }

                .delete-button {
                    width: 100%;
                    justify-self: end;

                    grid-column: 3 / 4;
                    grid-row: 1 / 3;
                }
            </style>
        `;
    }

    /**
     * Initializes the component by setting up event listeners for the task list.
     * 
     * - Selects the task list element from the shadow DOM.
     * - Adds a click event listener to the toggle done button to toggle the task's done state.
     * - Adds a click event listener to the delete button to delete the task.
     */
    initComponent() {
        this.$tag = this.shadowDOM.querySelector('.task-list');

        this.shadowDOM.querySelector('.toggle-done-button').addEventListener('click', () => {
            this.toggleDone();
        });

        this.shadowDOM.querySelector('.delete-button').addEventListener('click', () => {
            this.deleteTask();
        });
    }

    /**
     * Called when the element is disconnected from the document's DOM.
     * This method removes the element from the DOM.
     */
    disconnectedCallback() {
        this.remove()
    }

    /**
     * Deletes a task by its task ID.
     * 
     * This function sends a DELETE request to the server to remove the task with the specified task ID.
     * If the deletion is successful, it dispatches a custom event 'signal:task-deleted' with the task ID as the detail.
     * If the deletion fails, it alerts the user with an error message.
     * 
     * @async
     * @function deleteTask
     * @returns {Promise<void>} A promise that resolves when the task is deleted or an error occurs.
     */
    async deleteTask() {
        const taskId = this.attributes['task-id'].value;

        const response = await fetch(`${API_URL}/tasks/${taskId}`, {
            method: 'DELETE'
        });

        if (!response.ok) {
            alert('Error deleting task');
            return;
        }

        document.dispatchEvent(new CustomEvent('signal:task-deleted', {
            detail: taskId
        }));
    }

    /**
     * Toggles the 'done' status of a task by sending a PATCH request to the server.
     * Dispatches a custom event 'signal:task-toggle-done' with the task ID upon success.
     * Alerts the user if there is an error updating the task.
     *
     * @async
     * @function toggleDone
     * @returns {Promise<void>}
     */
    async toggleDone() {
        const taskId = this.attributes['task-id'].value;
        const taskDone = this.attributes.done.value;

        const response = await fetch(`${API_URL}/tasks/${taskId}`, {
            method: 'PATCH',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                done: taskDone === 'true' ? false : true
            })
        });

        if (!response.ok) {
            alert('Error updating task');
            return;
        }

        document.dispatchEvent(new CustomEvent('signal:task-toggle-done', {
            detail: taskId
        }));
    }
}

export default Task;